// client/vue-spa/root.vue
<template>
    <div class="content">
        <h1>Hello Vue 2 spa</h1>
        <div><img :src="imgSrc" width="100px"></div>
        <a href="/react-spa">from vue to react</a>
        <div class="input-group">
            Name: <input type="text" v-model="name">
            Age: <input type="text" v-model="age">
        </div>
        <div class="btn-group">
            <button @click="getUsers">Get users list</button>
            <button @click="delUser" :disabled="activeId === 0">Delete user</button>
            <button @click="addUser">Add user</button>
        </div>
        <table class="table">
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Age</th>
            </tr>
            </thead>
            <tbody>
            <template v-if="users.length > 0">
                <tr v-for="item in users" @click="activeId = item.id" :class="{'active':item.id === activeId}">
                    <td>{{item.id}}</td>
                    <td>{{item.name}}</td>
                    <td>{{item.age}}</td>
                </tr>
            </template>
            <template v-else>
                <tr>
                    <td colspan="3">Not data</td>
                </tr>
            </template>
            </tbody>
        </table>
    </div>
</template>

<script>
  import src from '../office365.png';

  export default {
    data () {
      return {
        imgSrc: src,
        users: [],
        activeId: 0,
        name: '',
        age: 0
      };
    },
    methods: {
      async getUsers () {
        this.users = await this.$http.get('users');
        this.activeId = 0;
      },
      async delUser () {
        await this.$http.delete(`users/${this.activeId}`);
        this.getUsers();
      },
      async addUser () {
        await this.$http.post('users', {
          name: this.name,
          age: this.age
        });
        this.getUsers();
      }
    }
  };
</script>

// client/react-spa/root.component.js
import React from 'react';
import src from '../office365.png';
import request from "./request";

export default class extends React.Component {
  state = {
    goodsList: [],
    activeId: 0,
    name: '',
    total: 0
  };
  
  componentDidCatch (error, errorInfo) {
    console.info(error, errorInfo);
  }
  
  changName = (e) => {
    e.persist();
    this.setState({
      name: e.target.value
    });
  };
  
  changeTotal = (e) => {
    e.persist();
    this.setState({
      total: e.target.value
    });
  };
  getGoods = async () => {
    const goodsList = await request.get('goods');
    this.setState({
      goodsList,
      activeId: 0
    });
  };
  delGoods = async () => {
    await request.delete(`goods/${this.state.activeId}`);
    this.getGoods();
  };
  addGoods = async () => {
    const { name, total } = this.state;
    await request.post('goods', {
      name,
      total
    });
    this.getGoods();
  };
  
  renderTableBody = () => {
    const { goodsList, activeId } = this.state;
    if (goodsList.length > 0) {
      return goodsList.map((goods, index) => {
        const { id, name, total, rest } = goods;
        return <tr key={index} onClick={() => this.changeActiveId(id)} className={activeId === id? 'active': ''}>
          <td>{id}</td>
          <td>{name}</td>
          <td>{total}</td>
          <td>{rest}</td>
        </tr>;
      });
    } else {
      return <tr>
        <td colSpan="4">Not data</td>
      </tr>;
    }
  };
  
  changeActiveId = (id) => {
    this.setState({
      activeId: id
    });
  };
  
  render () {
    const { name, total, activeId } = this.state;
    return (
      <div className="content">
        <h1>Hello React 16 spa</h1>
        <div><img src={src} width="100px"/></div>
        <a href="/vue-spa">from vue to vue</a>
        <div className="input-group">
          Name: <input type="text" value={name} onChange={this.changName}/>
          Total: <input type="text" value={total} onChange={this.changeTotal}/>
        </div>
        <div className="btn-group">
          <button onClick={this.getGoods}>Get goods list</button>
          <button onClick={this.delGoods} disabled={activeId === 0}>Delete goods</button>
          <button onClick={this.addGoods}>Add goods</button>
        </div>
        <table className="table">
          <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Total</th>
            <th>Rest</th>
          </tr>
          </thead>
          <tbody>
          {this.renderTableBody()}
          </tbody>
        </table>
      </div>
    );
  }
}
