// client/vue-spa/root.vue
<template>
    <div class="content">
        <h1 @click="test">Hello from Vue 2 spa</h1>
        <a href="/react-spa">from vue to react</a>
    </div>
</template>

<script>
  export default {
    methods:{
      async test(){
        let result = await this.$http.get('users');
        console.info(result)
      }
    }
  }
</script>

// src/react/root.component.js
import React from 'react';

export default class rootComponent extends React.Component {
  componentDidCatch (error, errorInfo) {
    console.info(error, errorInfo);
  }

  render () {
    return (
      <div className={'content'}>
        <h1>Hello from React</h1>
        <a href="/vue">from vue to vue</a>
      </div>
    );
  }
}
